Fix -Wnontrivial-memcall warning
Memcall functions work at the byte level so they don't know about
C++semantics and these C++ objects might not have trivial constructors
or destructors. I silenced the warning by explicitly casting the pointer
to void* with static_cast. I did this fix because it seems the code
developer knows the consequences with using memcall functions with C++
objects.

external/XMP-Toolkit-SDK/XMPFiles/source/FormatSupport/TIFF_Support.hpp:941:13:
error: first argument in call to 'memcpy' is a pointer to non-trivially
copyable type 'TIFF_FileWriter::InternalTagInfo'
[-Werror,-Wnontrivial-memcall]
  941 |                         memcpy ( this, &in, sizeof(*this) );
// AUDIT: Use of sizeof(InternalTagInfo) is safe.
      |                                  ^

external/XMP-Toolkit-SDK/XMPFiles/source/FormatSupport/PSIR_Support.hpp:289:13:
error: first argument in call to 'memcpy' is a pointer to non-trivially
copyable type 'PSIR_FileWriter::InternalRsrcInfo'
[-Werror,-Wnontrivial-memcall]
  289 |                         memcpy ( this, &in, sizeof(*this) );
// AUDIT: Use of sizeof(InternalRsrcInfo) is safe.
      |                                  ^